version: "3"

services:
  web:
    container_name: news-web
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    environment:
       - NODE_ENV=development 
       - WATCHPACK_POLLING=true
       - DATABASE_URL=${INTERNAL_NETWORK_DATABASE_URL}
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./rss-importer:/app/rss-importer
      - ./prisma:/app/prisma
    restart: always
    depends_on:
      - db
      - minio
    ports:
      - 3000:3000
      - 5001:5001
    networks:
      - my_network
  db:
    image: postgres:15.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my_network
  minio:
    container_name: s3minio
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres-data:
  minio_storage: