version: "3"

services:
  web:
    container_name: news-web
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      args:
        DATABASE_URL: ${INTERNAL_NETWORK_DATABASE_URL}
    environment:
       - NODE_ENV=production 
       - DATABASE_URL=${INTERNAL_NETWORK_DATABASE_URL}
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - minio
    ports:
      - 3000:3000
    networks:
      - my_network
  db:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my_network
  minio:
    container_name: s3minio
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
      MINIO_DEFAULT_BUCKETS: ${S3_BUCKET_NAME}
      MINIO_REGION: ${S3_REGION}
    volumes:
      - minio_storage:/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres-data:
  minio_storage: