version: "3"

services:
  web:
    container_name: news-web
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    environment:
       - NODE_ENV=production 
       - DATABASE_URL=${INTERNAL_NETWORK_DATABASE_URL}
    env_file:
      - .env.local
    restart: always
    depends_on:
      - db
      - minio
    ports:
      - 3000:3000
    networks:
      - my_network
  db:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my_network
  minio:
    container_name: s3minio
    image: bitnami/minio:latest
    volumes:
      - minio_storage:/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres-data:
  minio_storage: